<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="39166" started-at="2020-04-24T15:50:00Z" finished-at="2020-04-24T15:50:39Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="39166" started-at="2020-04-24T15:50:00Z" finished-at="2020-04-24T15:50:39Z">
      <class name="com.signinpage.using_listener_demo.SignInwithCredential">
        <test-method status="FAIL" signature="signInwithValid_mobileNumber()[pri:1, instance:com.signinpage.using_listener_demo.SignInwithCredential@4501b7af]" name="signInwithValid_mobileNumber" duration-ms="22234" started-at="2020-04-24T15:50:00Z" finished-at="2020-04-24T15:50:22Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.goibibo.keywords.Keywords.clickOnElement1(Keywords.java:254)
at com.signinpage.using_listener_demo.SignInwithCredential.signInwithValid_mobileNumber(SignInwithCredential.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signInwithValid_mobileNumber -->
        <test-method status="PASS" signature="loginWithfacebook()[pri:2, instance:com.signinpage.using_listener_demo.SignInwithCredential@4501b7af]" name="loginWithfacebook" duration-ms="16846" started-at="2020-04-24T15:50:22Z" finished-at="2020-04-24T15:50:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWithfacebook -->
      </class> <!-- com.signinpage.using_listener_demo.SignInwithCredential -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
